#==================MUIU[木鱼]===================
#
# 木鱼,语言分析插件
# 恰饭博客:https://blog.minloha.cn
#   使用方法: 在下方的anti列表里加入一定量自己要屏蔽的带有!!!强烈感情色彩!!!的词语(不知道什么是强烈感情色彩的话去百度)
#   文本相似度修改介绍:
#       文本相似度指玩家发送的聊天所带有的情感色彩与anti列表所有的样本相似度最高的一个
#       相似度约高,返回的数值越大.换言之,如果想要放宽限制,就把数值调大
#   只要词库够强大,抵挡全部素质人
#
# 对于导出禁言记录以及封禁记录的设置,必须认真看我
# 下载模板文件,后缀名为tmp,并将其放入配置文件目录下即可,切记,模板文件默认名称为index.tmp,如果自行修改将会无法加载模板
# 导出的html文件存放在配置文件目录下的 out 文件夹,当前版本只能离线查看,预计在下个版本填坑
# 导出html的命令只允许在控制台执行!!!!!!!!!!!!!!!!!!
#
# 对于测试key
#    在此承诺,测试密钥免费发放,如果遇到私自售卖的行为，切勿相信
#    密钥插件下载前往QQ群聊 :907661938,专属测试密钥询问Minloha免费生成
#
#权限组:
#  muiu.unban:
#    description: 解除封禁权限
#  muiu.morbid:
#    description: 禁言权限
#  muiu.mospk:
#    description: 解除禁言权限
#  muiu.seeList:
#    description: 查看禁言列表
#  muiu.alert:
#    description: 向玩家弹框
#
# 证书校验:
#   玩家可能会发送一些带有网址的消息,开启就是检验这些网址是否安全.当然也可以在敏感词列表添加网址
#==========================================
# 关于对话机器人的配置:
#     插件启动并运行后会在配置文件目录下生成名为robot.yml的配置文件,只需在内部添加对应的列表即可
#     添加示例:(列表名必须严格按照示例写)
#     允许使用彩色字符
# thesaurusize: 2          词库大小,存储的应答有多少个就写多少个
# 0:
#   back: "对不起,你说的这个问题我不知道≧_≦"
# 1:
#   question: "你是谁?"
#   back: "我是Mspirit!"
#
# 继续向下就按数字向下排序就行
# !!必须注意,0号为只能是当找不到词库内容时做出的应答
# !!注意: 如果不按格式编辑就会出现各种报错
# 实在不会写可以前往下载示例
#==========================================
# 因为我的css实在太差了,所以既然写不好就干脆不写
# 登录需要在url修改参数,比如本地连接
# 最后会出现: https://127.0.0.1:23456?brmv=XXXXXXXX&name=&+password=#
# 如果要顺利删除,只需要在name=之后加入你的账户,在password=之后加入密码,然后访问即可
#===========================================
# http服务启动在配置文件目录下的start.cmd
# html列表,一切账户都要在此注册
# 在里面写入你在下面注册的账户密码的父名称
serverAdmins:
  - "admins"
  - "admin2"
# 写入你自己的账户与密码
admins:
  - name: 'adm1n'
    password: 'passw0rd'
admin2:
  - name: 'super'
    password: '123456'
# 伪动态刷新时长,单位(秒)
time: 300
# 对于网站安全检查,超过下方的数字将停止获取,单位为毫秒   毫秒=秒数*1000
timeout: 5000
# 文本相似度,不推荐修改,过大不屏蔽,过小屏蔽过多.
contain: 0.3162277
# 玩家获取当前插件相关信息
isallows: true
# 是否开启证书校验功能,一般默认开启
cerKey: true
# 管理端口(大于25565小于65535的未使用端口)
port: 23456
# 测试密钥,功能已关闭,留着纪念一下
private_key:
# 敏感词,主要写关键词,不需要写的特别长,找到主谓宾写里面就可以(高效)
anti:
  - "wdnmd菜鸡LL"
  - "野爹fuck"
  - "crnmsl"
  - "ntsb"
  - "真牛哦也不厉害"
  - "傻逼脑瘫"
  - "你爸妈死了"
  - "大神又开始了呢"
  - "艹草你妈爸小弟弟"
  - "你爷爷祖宗"
  - "把你全家骨灰都扬咯"
  - "人类面临世界危机,将会绝种"
  - "新型冠状病毒是中国病毒"
  - "超级多黑卡等你挑选包退包换"
  - "正版迁移账户在线购买"
  - "双亲健在"
  - "外g挂纪司马死爸妈"
  - "我卧草操尼玛"
  - "没有母亲父亲双亲"
  - "野爹种缺爱轮奸上"
  - "哥哥操草我妹妹"
  - "火速加群购买最新暴力黑客吊打内部配置"

# 都看到这里了,不如做一下备份吧~